# Generated by Django 5.0 on 2024-01-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiondet',
            old_name='cab_id',
            new_name='cab',
        ),
    ]
