# Generated by Django 5.0 on 2024-01-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondet',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
