# Generated by Django 5.0 on 2023-12-28 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_product_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="nombre",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="nombre",
            new_name="name",
        ),
    ]
